//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package api

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInfo) DeepCopyInto(out *DeviceInfo) {
	*out = *in
	out.VirtualizationCapabilities = in.VirtualizationCapabilities
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeviceNode != nil {
		in, out := &in.DeviceNode, &out.DeviceNode
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeviceEnv != nil {
		in, out := &in.DeviceEnv, &out.DeviceEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInfo.
func (in *DeviceInfo) DeepCopy() *DeviceInfo {
	if in == nil {
		return nil
	}
	out := new(DeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUUsageMetrics) DeepCopyInto(out *GPUUsageMetrics) {
	*out = *in
	if in.ExtraMetrics != nil {
		in, out := &in.ExtraMetrics, &out.ExtraMetrics
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUUsageMetrics.
func (in *GPUUsageMetrics) DeepCopy() *GPUUsageMetrics {
	if in == nil {
		return nil
	}
	out := new(GPUUsageMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mount) DeepCopyInto(out *Mount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mount.
func (in *Mount) DeepCopy() *Mount {
	if in == nil {
		return nil
	}
	out := new(Mount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessInformation) DeepCopyInto(out *ProcessInformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessInformation.
func (in *ProcessInformation) DeepCopy() *ProcessInformation {
	if in == nil {
		return nil
	}
	out := new(ProcessInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualizationCapabilities) DeepCopyInto(out *VirtualizationCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualizationCapabilities.
func (in *VirtualizationCapabilities) DeepCopy() *VirtualizationCapabilities {
	if in == nil {
		return nil
	}
	out := new(VirtualizationCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerAllocation) DeepCopyInto(out *WorkerAllocation) {
	*out = *in
	if in.WorkerInfo != nil {
		in, out := &in.WorkerInfo, &out.WorkerInfo
		*out = new(WorkerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceInfos != nil {
		in, out := &in.DeviceInfos, &out.DeviceInfos
		*out = make([]*DeviceInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DeviceInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make([]*Mount, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Mount)
				**out = **in
			}
		}
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]*DeviceSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DeviceSpec)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerAllocation.
func (in *WorkerAllocation) DeepCopy() *WorkerAllocation {
	if in == nil {
		return nil
	}
	out := new(WorkerAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerInfo) DeepCopyInto(out *WorkerInfo) {
	*out = *in
	if in.AllocatedDevices != nil {
		in, out := &in.AllocatedDevices, &out.AllocatedDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllocatedDeviceUUIDs != nil {
		in, out := &in.AllocatedDeviceUUIDs, &out.AllocatedDeviceUUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Requests.DeepCopyInto(&out.Requests)
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerInfo.
func (in *WorkerInfo) DeepCopy() *WorkerInfo {
	if in == nil {
		return nil
	}
	out := new(WorkerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerMetrics) DeepCopyInto(out *WorkerMetrics) {
	*out = *in
	if in.ExtraMetrics != nil {
		in, out := &in.ExtraMetrics, &out.ExtraMetrics
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerMetrics.
func (in *WorkerMetrics) DeepCopy() *WorkerMetrics {
	if in == nil {
		return nil
	}
	out := new(WorkerMetrics)
	in.DeepCopyInto(out)
	return out
}
